### ISSUE TITLE
fix css for body

### ISSUE THREAD

**Issue by patraanjan23** [patraanjan23/timetable#2]
the body uses css grid to center the children. there is an issue where in large screen the h1 and table has too much gap between them. could be solved with grid adjustment or wrapping the whole h1 and table inside a single div.

**Comment by jasmine1601** [comment]
I can fix this.

**Comment by patraanjan23** [comment]
Okay assigned.

**Comment by patraanjan23** [comment]
accepted after resolving merge conflict. thank you.
